workflow Trial 6

diff --git a/.github/workflows/pythonanywhere.yaml b/.github/workflows/pythonanywhere.yaml
--- a/.github/workflows/pythonanywhere.yaml
+++ b/.github/workflows/pythonanywhere.yaml
@@ -36,3 +36,9 @@ jobs:
       run: |
         RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_APP_NAME }}/reload/ -H "Authorization: Token $API_TOKEN")
         echo "Reload response: $RESPONSE"
+        if [ "$RESPONSE" -eq 200 ]; then
+          echo "Reloaded successfully!"
+        else
+          echo "Failed to reload. Response code: $RESPONSE"
+          exit 1
+        fi
